#!/usr/bin/env python3
import csv, json, re, sys
from collections import defaultdict
from pathlib import Path

if len(sys.argv) != 2:
    raise SystemExit('usage: v51_runtime_tables.py <analysis-output-dir>')
root=Path(sys.argv[1])

def rows(name):
    p=root/name
    if not p.exists() or p.stat().st_size==0:return []
    with p.open(encoding='utf-8',errors='replace',newline='') as f:return list(csv.DictReader(f))

def canon(x):
    try:return f'{int((x or "").strip(),16):08X}'
    except Exception:return (x or '').strip().upper()

def split_ops(s):
    out=[];cur=[];depth=0
    for ch in s or '':
        if ch in '[{(':depth+=1
        elif ch in ']})':depth=max(0,depth-1)
        if ch==',' and depth==0:out.append(''.join(cur).strip());cur=[]
        else:cur.append(ch)
    if cur:out.append(''.join(cur).strip())
    return out

cands=rows('v5_runtime_table_candidates.csv')
if not cands:
    # Produce deterministic empty outputs so the workflow can still validate this stage.
    cands=[]

ins=[]
p=root/'disassembly.txt'
if p.exists():
    with p.open(encoding='utf-8',errors='replace') as f:
        for line in f:
            parts=line.rstrip('\n').split('\t',2)
            if len(parts)<3:continue
            try:addr=int(parts[0].strip(),16)
            except ValueError:continue
            fn=parts[1].strip();text=parts[2].strip();xs=text.split(None,1)
            if not xs:continue
            ins.append({'addr':addr,'fn':fn,'mnem':xs[0].upper(),'ops':xs[1].strip() if len(xs)>1 else '','text':text})

refs=[];writers=[]
for c in cands:
    try:table=int(c.get('table_address') or '0',16)
    except ValueError:continue
    page=table & ~0xfff; off=table & 0xfff
    for i,x in enumerate(ins):
        if x['mnem']!='ADRP':continue
        op=split_ops(x['ops'])
        if len(op)<2:continue
        m=re.search(r'0x([0-9a-fA-F]+)',op[1])
        if not m or int(m.group(1),16)!=page:continue
        reg=op[0].strip().upper()
        exact=False;build_end=i
        for j in range(i+1,min(len(ins),i+14)):
            y=ins[j]
            if y['fn']!=x['fn']:break
            yop=split_ops(y['ops'])
            if y['mnem']=='ADD' and len(yop)>=3 and yop[0].strip().upper()==reg and yop[1].strip().upper()==reg:
                mm=re.search(r'#?(0x[0-9a-fA-F]+|\d+)',yop[2])
                if mm and int(mm.group(1),0)==off:
                    exact=True;build_end=j;break
        if not exact and off!=0:continue
        refs.append({'table_address':f'{table:08X}','function_name':x['fn'],'address':f'{x["addr"]:08X}','kind':'base-construction','register':reg,'evidence':x['text']})
        for j in range(build_end+1,min(len(ins),build_end+28)):
            y=ins[j]
            if y['fn']!=x['fn']:break
            if reg not in y['ops'].upper():continue
            kind='use'
            if y['mnem'].startswith(('STR','STP','STUR','STXR','STLR')):kind='store'
            elif y['mnem'].startswith(('LDR','LDP','LDUR','LDXR','LDAR')):kind='load'
            refs.append({'table_address':f'{table:08X}','function_name':y['fn'],'address':f'{y["addr"]:08X}','kind':kind,'register':reg,'evidence':y['text']})
            if kind=='store':
                writers.append({'table_address':f'{table:08X}','function_name':y['fn'],'store_address':f'{y["addr"]:08X}','register':reg,'evidence':y['text'],'confidence':'medium-static' if exact else 'low-static'})

fields=['table_address','function_name','address','kind','register','evidence']
with (root/'v51_table_static_refs.csv').open('w',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(refs)
fields2=['table_address','function_name','store_address','register','evidence','confidence']
with (root/'v51_table_writer_candidates.csv').open('w',encoding='utf-8',newline='') as f:
    w=csv.DictWriter(f,fieldnames=fields2);w.writeheader();w.writerows(writers)

source=(root/'source_path.txt').read_text(errors='ignore').strip() if (root/'source_path.txt').exists() else ''
module=Path(source).name or 'target.so'
probe=[]
for c in cands[:200]:
    try:va=int(c.get('table_address') or '0',16)
    except ValueError:continue
    try:n=min(max(int(float(c.get('max_index') or 0))+1,1),128)
    except Exception:n=16
    probe.append({'function_entry':canon(c.get('function_entry')),'branch_address':canon(c.get('branch_address')),'va':va,'count':n,'pattern':c.get('pattern','')})
js=f'''// Generated by Mobile Ghidra Lab V5.1. Read-only runtime table probe.\n'use strict';\nconst MODULE_NAME = {json.dumps(module)};\nconst CANDIDATES = {json.dumps(probe)};\nfunction insideModule(m,p) {{ const x=ptr(p); return x.compare(m.base)>=0 && x.compare(m.base.add(m.size))<0; }}\nrpc.exports = {{\n  probe() {{\n    const m=Process.findModuleByName(MODULE_NAME); if(!m) throw new Error('module not loaded: '+MODULE_NAME);\n    const out=[];\n    for(const c of CANDIDATES) {{\n      const table=m.base.add(c.va); const entries=[];\n      for(let i=0;i<c.count;i++) {{\n        try {{ const rel=table.add(i*4).readS32(); const target=table.add(rel); entries.push({{i,rel,target:target.toString(),inModule:insideModule(m,target)}}); }}\n        catch(e) {{ entries.push({{i,error:String(e)}}); break; }}\n      }}\n      out.push({{...c,table:table.toString(),entries}});\n    }}\n    return {{module:MODULE_NAME,base:m.base.toString(),size:m.size,candidates:out}};\n  }},\n  watchmprotect() {{\n    const m=Process.findModuleByName(MODULE_NAME); if(!m) throw new Error('module not loaded: '+MODULE_NAME);\n    const p=Module.findGlobalExportByName('mprotect'); if(!p) return false;\n    Interceptor.attach(p,{{onEnter(args){{this.a=args[0];this.n=args[1].toUInt32();this.prot=args[2].toInt32();}},onLeave(ret){{if(insideModule(m,this.a)) send({{kind:'mprotect',address:this.a.toString(),length:this.n,prot:this.prot,result:ret.toInt32()}});}}}});\n    return true;\n  }}\n}};\n'''
(root/'v51_runtime_table_probe.js').write_text(js,encoding='utf-8')
with (root/'v51_runtime_table_report.md').open('w',encoding='utf-8') as w:
    w.write('# V5.1 runtime-table follow-up\n\n')
    w.write(f'- Runtime/transformed table candidates: **{len(cands)}**\n- Static base references recovered: **{len(refs)}**\n- Static store candidates near table bases: **{len(writers)}**\n- Generated read-only Frida table probe entries: **{len(probe)}**\n\n')
    w.write('Static writer hits are evidence candidates, not proof that the store initializes the dispatcher table. If static bytes remain invalid, run the generated probe after the module has initialized and compare runtime entries with executable module addresses.\n')
print(json.dumps({'tables':len(cands),'static_refs':len(refs),'writer_candidates':len(writers),'probe_tables':len(probe)}))
